export const projectsData = [
  {
    id: 1,
    image: '/images/portfolio.png',
    title: 'Portfolio',
    subtitle: 'Webpage / 3D Modeling',
    text: 'I build this 3D integrated wepsite using Spline and Next.js. I choose Spline for 3D modeling beacouse its a simple way of creatind 3d screens with states and events. For now Next.js is for me the top framework, i tryed to take advatages of server components as much as posible',
    tech: ['Next.js', 'Spline', 'Typescript', 'Tailwind', 'Framer Motion'],
  },
  {
    id: 2,
    image: '/images/tamtu.png',
    title: 'Tamtu Multi City Games',
    subtitle: 'Webpage',
    text: 'It was my individual project that I created using Next.js(14). The page content is fetched using Axios and GraphQL from DirectusCMS. The subscription form i handled by React Hook Form',
    tech: [
      'Next.js',
      'Typescript',
      'Tailwind',
      'React Hook Form',
      'Axios',
      'GraphQL',
      'Postman',
      'Directus',
    ],
  },
  {
    id: 3,
    image: '/images/furgonetka.png',
    title: 'Portmonetka - wtyczka checkout',
    text: 'Samodzielnie stworzyłem MVP Front-endu',
    tech: ['React', 'React Router', 'Styled Components'],
  },
  {
    id: 4,
    image: '/images/skydental.png',
    title: 'Skydental - webpage',
    subtitle: 'Webpage',
    text: 'Beautifull modern page with a cool particles effect. I created this project using Next.js(12)',
    link: 'https://skydentalclinic.pl/',
    tech: [
      'Next.js',
      'Typescript',
      'React Query',
      'Styled Components',
      'GraphQL',
      'Directus',
      'Framer Motion',
    ],
  },
  {
    id: 5,
    image: '/images/brainforge.png',
    title: 'BrainforgeIT - webpage',
    text: 'Strona wykonana wspólnie ',
    tech: [
      'next.js',
      'typescript',
      'react query',
      'Styled components',
      'GraphQL',
      'Directus',
      'framer motion',
    ],
  },
  {
    id: 6,
    image: '/images/prete.png',
    title: 'Prete - e-commerce',
    text: 'sklep z biżuterią',
    tech: [
      'next.js',
      'typescript',
      'react query',
      'Styled components',
      'GraphQL',
      'Vendure',
    ],
  },
  {
    id: 7,
    image: '/images/panele.png',
    title: 'Hurtownia fotowoltaiczna',
    text: 'Przejąłem gotowy projekt. Zajmowałem się naprawą błędów oraz rozwijałem nowe funkcjonalności zarówno na frontendzie jak i backendzie',
    tech: ['vue', 'vuex', 'Axios', 'Vuetify', 'node'],
  },
  {
    id: 8,
    image: '/images/panele-montaz.png',
    title: 'Panel zarządzania pracami wykonawczymi',
    text: 'Przejąłem projekt w trakcie tworzenia. Zajmowałem się dokończeniem projektu zarówno na frontendzie jak i backendzie',
    tech: ['vue', 'vuex', 'Axios', 'Vuetify', 'node', 'typescript'],
  },
  {
    id: 9,
    image: '/images/tixe.png',
    title: 'Tixe-Wash - admin panel',
    text: 'Przy tworzeniu panelu zarządzania, byłem odpowiedzialny za część dotyczącą użytkowników.',
    tech: ['next', 'MaterialUI', 'react query', 'Tailwind'],
  },
];
